// The GPL version 3 License (GPLv3)
// 
// Copyright (c) 2019 vtdev.com
// This file is part of the CEX Cryptographic library.
// 
// This program is free software : you can redistribute it and / or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//
// 
// Implementation Details:
// An implementation of an HMAC Counter Generator (HCG)
// Written by John Underhill, November 2, 2016
// Updated April 18, 2017
// Updated February 17, 2019
// Contact: develop@vtdev.com

#ifndef CEX_HCG_H
#define CEX_HCG_H

#include "DrbgBase.h"
#include "IDigest.h"
#include "IProvider.h"
#include "HMAC.h"
#include "SHA2Digests.h"

NAMESPACE_DRBG

using Enumeration::Digests;
using Digest::IDigest;
using Mac::HMAC;
using Provider::IProvider;
using Enumeration::Providers;
using Enumeration::SHA2Digests;

/// <summary>
/// An implementation of an HMAC Counter Generator DRBG: HCG
/// </summary> 
/// 
/// <example>
/// <description>Generate an array of pseudo-random bytes:</description>
/// <code>
/// HCG rnd(Digests::SHA512, [Providers::ACP]);
/// // initialize
/// rnd.Initialize(Key, [Nonce], [Info]);
/// // generate bytes
/// rnd.Generate(Output, [Offset], [Size]);
/// </code>
/// </example>
/// 
/// <remarks>
/// <description><B>Overview:</B></description>
/// <para>The HMAC based generator uses a hash function in a keyed HMAC to generate pseudo-random output. \n
/// The HMAC is initialized with the input key, when an entropy provider is specified, at intervals of ReseedThreshold,an internal key strengthening/derivation function extracts a key equal to the underlying hash functions internal block size,
/// this is the most secure key-size when generating pseudo-random using an HMAC. \n
/// The key derivation function takes as input the next unused pseudo-random state, which is finalized and added to the second half of the new key, and new entropy from the random provider, is used to populate the first half of the key. \n
/// The generator function uses the HMAC to process a state counter, (which can be set at initialization with the key containers Nonce parameter, or as a zeroed array of 8 bytes), 
/// the distribution code which consist of the library name, the classes formal name and security strength, (an optional info parameter can also be added to this using the Info parameter of the initialization key), and the current HMAC finalized state..
/// The Info parameter of the initialization key can be used as a secondary, static source of entropy used by the generate function, making this similar to an HKDF construction, (HCG uses an 8 byte counter instead of 1 byte used by HKDF, but otherwise the operation is nearly identical). 
/// The generator copies the HMAC finalized output to the internal state, and then to functions output array as requested. 
/// The pseudo-random state array is processed as seed material in the next iteration of the generation cycle, along with the counter and distribution code, in a continuous transformation process. \n
/// The state counter can be initialized by the Nonce parameter of the Initialize function to an 8 byte secret and random value, (this is strongly recommended). \n
/// The reseed-requests counter is incremented by the number of bytes processed by a generation call, if this value exceeds the ReseedThreshold value (100MB by default),
/// the generator finalizes the state (not added to output), and uses that state, along with the entropy provider, to create a new HMAC key. \n
/// The HMAC is then re-keyed, the reseed-requests counter is reset, and a new initial state is generated by the entropy provider for the next generation cycle.</para>
/// 
/// <description><B>Initialization and Update:</B></description>
/// <para>The Initialize functions have three different parameter options: the Key which is the primary key, 
/// the Nonce used to initialize the internal state-counter, and the Info which is used by the Generate function to pass a complete block to the HMAC update function. \n
/// The Key value must be one of the LegalKeySizes() in length, and must be a secret and random value. \n
/// The eight byte (NonceSize) Nonce value is another secret value, used to initialize the internal state counter to a non-zero random value. \n
/// The Info parameter maps to the DistributionCode() property, and is used as message state when generating the pseudo-random output. \n
/// The Info is recommended, and for best security, should be secret, random, and should be no more than 20 bytes in length \n 
/// The Update function uses the seed value to re-key the HMAC via the internal key derivation function. \n
/// The update functions Key parameter, must be a random seed value equal in length to the seed used to initialize the generator.</para>
///
/// <description><B>Predictive Resistance:</B></description>
/// <para>Predictive and backtracking resistance prevent an attacker who has gained knowledge of generator state at some time from predicting future or previous outputs from the generator. \n
/// The optional resistance mechanism uses an entropy provider to add seed material to the generator, this new seed material is passed through the derivation function along with the current state, 
/// the output hash is used to reseed the generator. \n
/// The default interval at which this reseeding occurs is 1000 times the digest output size in bytes, but can be set using the ReseedThreshold() property; once this number of bytes or greater has been generated, 
/// the seed is regenerated. \n 
/// Predictive resistance is strongly recommended when producing large amounts of pseudo-random (10kb or greater).</para>
///
/// <description>Implementation Notes:</description>
/// <list type="bullet">
/// <item><description>This implementation only supports the SHA2-256 and SHA2-512 message digests.</description></item>
/// <item><description>The class constructor can either be initialized with message digest and entropy provider instances, or using the Digests and Providers enumeration names.</description></item>
/// <item><description>Digest and provider instances created using the enumeration constructor, are automatically deleted when the class is destroyed.</description></item>
/// <item><description>The generator can be initialized with either a SymmetricKey key container class, or with a Key and optional inputs of Nonce and Info.</description></item>
/// <item><description>The LegalKeySizes() property contains a list of the supported seed input sizes.</description></item>
/// <item><description>There are three legal seed sizes; the first (smallest) is the minimum required key size, the second the recommended size, and the third is maximum security.</description></item>
/// <item><description>Initializing with a Nonce is recommended; the nonce value must be random, secret, and 8 bytes in length.</description></item>
/// <item><description>The Info value (DistributionCode) is also recommended; for best security, this value should be secret, random, and DistributionCodeMax() in length.</description></item>
/// <item><description>The Generate() methods can not be used until an Initialize() function has been called, and the generator is seeded.</description></item>
/// <item><description>The Update() method requires a Key of length equal to the seed used to initialize the generator.</description></item>
/// </list>
/// 
/// <description>Guiding Publications:</description>
/// <list type="number">
/// <item><description>NIST <a href="http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-90Ar1.pdf">SP800-90A R1</a>.</description></item>
/// <item><description>NIST <a href="http://csrc.nist.gov/publications/nistpubs/800-90A/SP800-90A.pdf">SP800-90A</a></description>.</item>
/// <item><description>BouncyCastle <a href="https://github.com/bcgit/bc-java/blob/ae63147936376e85e068c7b63373d4e930c3fe58/core/src/main/java/org/bouncycastle/crypto/prng/DigestRandomGenerator.java">DigestRandomGenerator.java</a>: Section 10.1</description>.</item>
/// <item><description>Security Analysis for <a href="https://tel.archives-ouvertes.fr/tel-01236602/document">Pseudo-Random Numbers Generators</a></description>.</item>
/// <item><description>NIST <a href="http://csrc.nist.gov/publications/drafts/800-90/draft-sp800-90b.pdf">SP800-90B</a>: Recommendation for the Entropy Sources Used for Random Bit Generation.</description></item>
/// <item><description>NIST <a href="http://csrc.nist.gov/publications/fips/fips140-2/fips1402.pdf">Fips 140-2</a>: Security Requirments For Cryptographic Modules.</description></item>
/// <item><description>NIST <a href="http://eprint.iacr.org/2006/379.pdf">Security Bounds</a> for the Codebook-based: Deterministic Random Bit Generator.</description></item>
/// </list>
/// </remarks>
class HCG final : public DrbgBase
{
private:

	static const size_t COUNTER_SIZE = 8;
	// 100mb: default before reseeded internally
	static const size_t DEF_RESEED = 102400000;
	// 10gb: maximum before rekey is required
	static const ulong MAX_OUTPUT = 10240000000;
	// 100mb: maximum size of a single request
	static const size_t MAX_REQUEST = 102400000;
	// 1024: maximum reseed calls before exception
	static const size_t MAX_THRESHOLD = 1024;
	// the minimum key length that will initialize the generator
	static const size_t MINKEY_LENGTH = 16;

	class HcgState;
	std::unique_ptr<HMAC> m_hcgGenerator;
	std::unique_ptr<IProvider> m_hcgProvider;
	std::unique_ptr<HcgState> m_hcgState;
	bool m_isDestroyed;
	bool m_isInitialized;

public:

	//~~~Constructor~~~//

	/// <summary>
	/// Copy constructor: copy is restricted, this function has been deleted
	/// </summary>
	HCG(const HCG&) = delete;

	/// <summary>
	/// Copy operator: copy is restricted, this function has been deleted
	/// </summary>
	HCG& operator=(const HCG&) = delete;

	/// <summary>
	/// Default constructor: default constructor is restricted, this function has been deleted
	/// </summary>
	HCG() = delete;

	/// <summary>
	/// Instantiate the class using a SHA2 digest type name, and an optional entropy source type
	/// </summary>
	///
	/// <param name="DigestType">The hash digests enumeration type name; SHA256/SHA512 are legal options</param>
	/// <param name="ProviderType">The enumeration type name of an entropy source; enables predictive resistance, the default is ACP</param>
	///
	/// <exception cref="CryptoGeneratorException">Thrown if an unrecognized digest type name is used</exception>
	explicit HCG(SHA2Digests DigestType, Providers ProviderType = Providers::ACP);

	/// <summary>
	/// Instantiate the class using a digest instance, and an optional entropy source 
	/// </summary>
	/// 
	/// <param name="Digest">The hash digest instance; SHA256/SHA512 are legal options</param>
	/// <param name="Provider">Provides an entropy source; enables predictive resistance, can be null</param>
	/// 
	/// <exception cref="CryptoGeneratorException">Thrown if a null digest is used</exception>
	explicit HCG(IDigest* Digest, IProvider* Provider = nullptr);

	/// <summary>
	/// Destructor: finalize this class
	/// </summary>
	~HCG() override;

	//~~~Accessors~~~//

	/// <summary>
	/// Read Only: Generator is ready to produce random
	/// </summary>
	const bool IsInitialized() override;

	/// <summary>
	/// Read/Write: The maximum output generated between auto-seed generation when using an entropy provider
	/// </summary>
	size_t &ReseedThreshold() override;

	/// <summary>
	/// Read Only: The estimated classical security strength in bits.
	/// <para>This value depends both on the hash function output size, and the number of bits used to seed the generator.</para>
	/// </summary>
	const size_t SecurityStrength() override;

	//~~~Public Functions~~~//

	/// <summary>
	/// Fill a standard-vector with pseudo-random bytes
	/// </summary>
	/// 
	/// <param name="Output">The output standard-vector to fill with random bytes</param>
	///
	/// <exception cref="CryptoGeneratorException">Thrown if the generator is not initialized, the output size is misaligned, 
	/// the maximum request size is exceeded, or if the maximum reseed requests are exceeded</exception>
	void Generate(std::vector<byte> &Output) override;

	/// <summary>
	/// Fill a secure-vector with pseudo-random bytes
	/// </summary>
	/// 
	/// <param name="Output">The output secure-vector to fill with random bytes</param>
	///
	/// <exception cref="CryptoGeneratorException">Thrown if the generator is not initialized, the output size is misaligned, 
	/// the maximum request size is exceeded, or if the maximum reseed requests are exceeded</exception>
	void Generate(SecureVector<byte> &Output) override;

	/// <summary>
	/// Fill a standard-vector with pseudo-random bytes using offset and length parameters
	/// </summary>
	/// 
	/// <param name="Output">The output standard-vector to fill with random bytes</param>
	/// <param name="OutOffset">The starting position within the output vector</param>
	/// <param name="Length">The number of bytes to generate</param>
	///
	/// <exception cref="CryptoGeneratorException">Thrown if the generator is not initialized, the output size is misaligned, 
	/// the maximum request size is exceeded, or if the maximum reseed requests are exceeded</exception>
	void Generate(std::vector<byte> &Output, size_t OutOffset, size_t Length) override;

	/// <summary>
	/// Fill a secure-vector with pseudo-random bytes using offset and length parameters
	/// </summary>
	/// 
	/// <param name="Output">The output secure-vector to fill with random bytes</param>
	/// <param name="OutOffset">The starting position within the output vector</param>
	/// <param name="Length">The number of bytes to generate</param>
	///
	/// <exception cref="CryptoGeneratorException">Thrown if the generator is not initialized, the output size is misaligned, 
	/// the maximum request size is exceeded, or if the maximum reseed requests are exceeded</exception>
	void Generate(SecureVector<byte> &Output, size_t OutOffset, size_t Length) override;

	/// <summary>
	/// Initialize the generator with a SymmetricKey structure containing the key, and optional nonce, and info string
	/// </summary>
	/// 
	/// <param name="Parameters">The SymmetricKey containing the generators keying material</param>
	/// 
	/// <exception cref="CryptoGeneratorException">Thrown if the seed is not a legal seed size</exception>
	void Initialize(ISymmetricKey &Parameters) override;

	/// <summary>
	/// Update the generators keying material, used to refresh the state
	/// </summary>
	///
	/// <param name="Key">The new seed value array</param>
	/// 
	/// <exception cref="CryptoGeneratorException">Thrown if the seed is too small</exception>
	void Update(const std::vector<byte> &Key) override;

	/// <summary>
	/// Update the generators keying material with a secure-vector key
	/// </summary>
	///
	/// <param name="Key">The secure-vector containing the new key material</param>
	/// 
	/// <exception cref="CryptoGeneratorException">Thrown if the key is too small</exception>
	void Update(const SecureVector<byte> &Key) override;

private:

	static void Derive(std::unique_ptr<HMAC> &Generator, std::unique_ptr<IProvider> &Provider, std::unique_ptr<HcgState> &State);
	static void Expand(std::unique_ptr<HMAC> &Generator, std::unique_ptr<HcgState> &State, std::vector<byte> &Output, size_t OutOffset, size_t Length);
	static void Fill(std::unique_ptr<HMAC> &Generator, std::unique_ptr<HcgState> &State);
};

NAMESPACE_DRBGEND
#endif
